name: aztec-stateless-prover
services:
  request-listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aztec_listener_container
    env_file:
      - .env 
    environment:
      MARKET_ID: "8"
      CHAIN_ID: "421614"
      PROOF_MARKETPLACE_ADDRESS: "0x0b6340a893B944BDc3B4F012e934b724c83abF97"
      GENERATOR_REGISTRY_ADDRESS: "0x5ce3e1010028C4F5687356D721e3e2B6DcEA7C25"
      START_BLOCK: "87455947"
      MAX_PARALLEL_PROOFS: "1" # one for now, one large machine more
      IVS_URL: "http://stateless-prover:8001/checkInput" #set this to same as stateless-prover now, which change latter once enclave is complete
      PROVER_URL: "http://stateless-prover:8001" #set this to same as stateless-prover now, which change latter
    depends_on:
      - stateless-prover
    restart: unless-stopped 
  stateless-prover:
    image: "aztecprotocol/aztec" #use the custom image provided by, if default one is used, it will fail
    volumes:
      - ./log/aztec-prover-agent/:/usr/src/yarn-project/aztec/log:rw
      - ./cache/bb-crs/:/root/.bb-crs:rw
      - ./workdir/bb-prover/:/usr/src/yarn-project/bb:rw
    command: [ "start", "--kalypso" ]
    restart: on-failure:5
